export class GlobalVariable {
  static readonly BREAK_POINT_KEY: string = "break_point" // 全局变量的key
  static readonly SAFE_AREA_BOTTOM: string = "safe_area_bottom" // 底部导航栏高度
  static readonly SAFE_AREA_TOP: string = "safe_area_top" // 顶部状态栏高度
  static readonly BASE_URL: string = "https://meikou-api.itheima.net" // 网络请求基础地址
  static readonly SUCCESS_CODE: string = "1" // 请求成功后的响应码
}

export class BusinessVariable {
  static readonly CATEGORY_DATA: string = "category" // 成功标识
}